[mcp_servers.supabase]
command = "npx"
args = [
  "-y",
  "@supabase/mcp-server-supabase",
  "--read-only"
]
startup_timeout_ms = 20000

[mcp_servers.supabase.env]
SUPABASE_ACCESS_TOKEN = "sbp_af575d8abfef44eb8688bff11ef48591b0e48ba6"
